import type { Metadata } from "next";
import "./globals.css";
import { ConditionalHeader } from "./component/ConditionalHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <ConditionalHeader />
        <div>{children}</div>
      </body>
    </html>
  );
}
